[package]
name = "telly-parser"
version = "0.1.0"
edition = "2021"
authors = ["Robert Li"]
description = "Struct-ure some filenames."
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
